In [44]:
#question1
import numpy as np
arr=np.arange(2,50,3)
print(arr)


[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


In [42]:
#question2
import numpy as np
l1=[12,46,15,67,45]
l2=[23,87,78,53,17]
arr1=np.asarray(l1)
arr2=np.asarray(l2)
arr=np.concatenate((arr1,arr2))
print(arr)
print(sorted(arr1))
print(sorted(arr2))
print(sorted(arr))


[12 46 15 67 45 23 87 78 53 17]
[12, 15, 45, 46, 67]
[17, 23, 53, 78, 87]
[12, 15, 17, 23, 45, 46, 53, 67, 78, 87]


In [46]:
#question3
arr=np.array([[10,20,30],
             [50,30,60],
             [40,80,90]])
print(arr)
print("dimension of the arr:",arr.shape)
print("size of the arr:",arr.size)


[[10 20 30]
 [50 30 60]
 [40 80 90]]
dimension of the arr: (3, 3)
size of the arr: 9


In [61]:
#question4
#using np.newaxis
import numpy as np
#creating 1d array
arr=np.arange(10)
print("shape of arr:",arr.shape)
#converting the 1d array to 2d array
#converting the row size using new axis
row_arr=arr[np.newaxis,:]
print("shape of row:",row_arr.shape)
#converting the column size using new axis
col_arr=arr[:,np.newaxis]
print("shape of column:",col_arr.shape)


shape of arr: (10,)
shape of row: (1, 10)
shape of column: (10, 1)


In [62]:
#question4
#using np.expand_dims
import numpy as np
#creating 1d array
arr=np.arange(10)
print("shape of arr:",arr.shape) 
#converting 1d array
#converting the row size using expand_dimension
row_arr=np.expand_dims(arr,axis=0)
print("shape of row:",row_arr.shape)
#converting the column size using expand_dimension
col_arr=np.expand_dims(arr,axis=1)
print("shape of column:",col_arr.shape)





shape of arr: (10,)
shape of row: (1, 10)
shape of column: (10, 1)


In [68]:
#question5
a=np.square([2,4,6,8,10])
b=np.square([1,3,7,9,11])
print("horizantally stacked:",np.hstack((a,b)))
print("vertically stacked:",np.vstack((a,b)))


horizantally stacked: [  4  16  36  64 100   1   9  49  81 121]
vertically stacked: [[  4  16  36  64 100]
 [  1   9  49  81 121]]


In [71]:
#question6
import numpy as np
list=[1,4,7,9,2,4,3,1,5,7,6,2,3]
x=np.array(list)
print("The unique elements in the list:",np.unique(x))
print("The length of unique list:",len(np.unique(x)))

        
    

The unique elements in the list: [1 2 3 4 5 6 7 9]
The length of unique list: 8
